- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Install basic packages
      become: true
      become_usr: root
      apt:
        name:
        - formiko 
        - fonts-firacode
        - tmux
        state: present
        update_cache: true
