- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - include: tasks/files.yml
    - include: tasks/addrepos.yml
    - include: tasks/packages.yml
