- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - import: tasks/addrepos
    - import: tasks/packages
    - name: Install basic packages
      become: true
      apt:
        name: tmux
	- formiko
	- fonts-firacode
	- tmux
        state: present
        update_cache: true
