- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False

  tasks:
    - name: Install basic packages
      become: true
      apt:
        name: tmux
        state: present
        update_cache: true
