- name: create ansible user
  user:
    name: ansible
    system: yes

- name: copy sudoers_ansible
  copy:
    src: files/sudoers_ansible
    dest: /etc/sudoers.d/ansible
    owner: root
    group: root
    mode: 0440

#- name: remove sudoers_ansible
#  file:
#    path: /etc/sudoers.d/ansible
#    state: absent
